
package Interface;

import BancoDados.ConexaoBancoDados;
import BancoDados.InteracaoBancoDados;
import java.awt.Toolkit;


/**
 *
 * @author Guu
 */
public class TelaJogoDificil extends javax.swing.JFrame {
    private String palavraChave;
    private StringBuilder palavraAdivinhada;
    private String letrasUsadas;
    private int tentativasRestantes;
    ConexaoBancoDados conexaoSQLite = new ConexaoBancoDados();
    InteracaoBancoDados interacaoBanco = new InteracaoBancoDados(conexaoSQLite);
    

    public TelaJogoDificil() {
        initComponents();
        setIcon();
        iniciarJogo();
    }
   
    private void iniciarJogo() {
        // Obter palavra-chave do banco de dados ou de outra fonte de dados
        palavraChave = interacaoBanco.consultaRegistroTabelaID();
        palavraAdivinhada = new StringBuilder("_".repeat(palavraChave.length()));
        letrasUsadas = "";
        tentativasRestantes = 5;
        
        atualizarPalavraForca();
    }
    
    private void atualizarPalavraForca() {
        palavraForca.setText(palavraAdivinhada.toString());
        //palavraForca.setText("Letras Usadas: " + letrasUsadas);
        labelTentativa.setText("Tentativas Restantes: " + tentativasRestantes);
    }

    
    private void registrarTentativa() {
    String letra = inputLetra.getText().toLowerCase();
    if (letra.length() == 1 && Character.isLetter(letra.charAt(0))) {
        realizarTentativa(letra.charAt(0));
    } else {
        labelFeedback.setText("Por favor, digite uma letra válida.");
    }
    inputLetra.setText(""); // Limpar o campo de entrada após a tentativa
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        palavraForca = new javax.swing.JLabel();
        inputLetra = new javax.swing.JTextField();
        dicaPalavra = new javax.swing.JLabel();
        labelTentativa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        palavraForca1 = new javax.swing.JLabel();
        labelFeedback = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman by The Snakes INC");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(46, 51, 47));

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo hangman.jpg"))); // NOI18N
        logo2.setText("tese");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hangman_1.png"))); // NOI18N
        jLabel1.setToolTipText("");

        palavraForca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        palavraForca.setForeground(new java.awt.Color(204, 204, 204));
        palavraForca.setText("_");

        inputLetra.setBackground(new java.awt.Color(46, 51, 47));
        inputLetra.setDocument(new javax.swing.text.PlainDocument());
        inputLetra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputLetra.setForeground(new java.awt.Color(255, 255, 255));
        inputLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLetraActionPerformed(evt);
            }
        });

        dicaPalavra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dicaPalavra.setForeground(new java.awt.Color(204, 204, 204));
        dicaPalavra.setText("DicaPalavra");

        labelTentativa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTentativa.setForeground(new java.awt.Color(204, 204, 204));
        labelTentativa.setText("Tentativas Restantes:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Digite uma letra:");

        jlabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(204, 204, 204));
        jlabel6.setText("Retorno:");

        palavraForca1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        palavraForca1.setForeground(new java.awt.Color(204, 204, 204));
        palavraForca1.setText("Palavra:");

        labelFeedback.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelFeedback.setForeground(new java.awt.Color(204, 204, 204));

        botaoVoltar.setBackground(new java.awt.Color(45, 197, 85));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(0, 0, 0));
        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelTentativa)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(inputLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(360, 360, 360))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dicaPalavra)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(palavraForca1)
                        .addGap(18, 18, 18)
                        .addComponent(palavraForca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabel6)
                        .addGap(18, 18, 18)
                        .addComponent(labelFeedback)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palavraForca)
                    .addComponent(palavraForca1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel6)
                    .addComponent(labelFeedback))
                .addGap(18, 18, 18)
                .addComponent(dicaPalavra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(labelTentativa)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLetraActionPerformed
        // TODO add your handling code here:
                registrarTentativa();

    }//GEN-LAST:event_inputLetraActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

     private void realizarTentativa(char letraTentada) {
        if (letrasUsadas.contains(String.valueOf(letraTentada))) {
            labelFeedback.setText("Você já tentou a letra '" + letraTentada + "'. Digite outra letra.");
        } else {
            letrasUsadas += letraTentada;
            if (palavraChave.contains(String.valueOf(letraTentada))) {
                for (int i = 0; i < palavraChave.length(); i++) {
                    if (palavraChave.charAt(i) == letraTentada) {
                        palavraAdivinhada.setCharAt(i, letraTentada);
                    }
                }
                if (!palavraAdivinhada.toString().contains("_")) {
                    // O jogador ganhou o jogo
                    labelFeedback.setText("Parabéns, Você acertou! A palavra é " + palavraChave);
                    // Implemente o que você deseja fazer após o jogador ganhar
                } else {
                    labelFeedback.setText("Muito bom! A letra '" + letraTentada + "' existe na palavra.");
                }
            } else {
                tentativasRestantes--;
                if (tentativasRestantes == 0) {
                    // O jogador perdeu o jogo
                    labelFeedback.setText("Você esgotou suas tentativas. A palavra era " + palavraChave);
                    inputLetra.setEnabled(false);
                    // Implemente o que você deseja fazer após o jogador perder
                } else {
                    labelFeedback.setText("A letra '" + letraTentada + "' não existe na palavra. Tente outra letra.");
                }
            }
        }
        atualizarPalavraForca();
    }

    
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogoDificil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel dicaPalavra;
    public static javax.swing.JTextField inputLetra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel labelFeedback;
    private javax.swing.JLabel labelTentativa;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel palavraForca;
    private javax.swing.JLabel palavraForca1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo hangman.png")));
    }
    
    public void setPalavraForca(String palavra) {
       palavraForca.setText(palavra);
    }

}

